# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version
      # Uncomment this step to verify the use of 'dart format' on each commit.
#      - name: Verify formatting
#        run: dart format --output=none --set-exit-if-changed .

#      - name: Get dependencies and generate mocks
#        run: |
#            flutter pub get
#            flutter pub run build_runner build
      - name: Generate Lint Report
        run: flutter analyze > lint-report.html

      - name: Upload Lint Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          - name: lint-report
            path: lint-report.html

#  lint:
#    needs: [ "build"]
#    runs-on: ubuntu-latest
#    steps:
#      - name: Run analyzer
#        run:  flutter analyze
#      - name: checkout code
#        uses:  actions/checkout@v3
#
#      - name: Generate Lint Report
#        run: flutter analyze > lint-report.html
#
#      - name: Upload Lint Report as Artifact
#        uses: actions/upload-artifact@v2
#        with:
#          - name: lint-report
#            path: lint-report.html


      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
#      - name: Run tests
#        run: flutter test
